version: '3.8'

services:
  # PostgreSQL 16
  database16:
    image: postgres:16-alpine
    container_name: database16
    environment:
      POSTGRES_DB: tipicos_tpi135
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
    ports:
      - "5432:5432"
    volumes:
      - ~/docker/volumes/postgresql16/data:/var/lib/postgresql/data
      - ./tipicos_tpi135_2025.sql:/docker-entrypoint-initdb.d/01-init.sql:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # pgAdmin 4 para gestión visual de la base
  pgadmin16:
    image: dpage/pgadmin4
    container_name: pgadmin16
    environment:
      PGADMIN_DEFAULT_EMAIL: fp20008@ues.edu.sv
      PGADMIN_DEFAULT_PASSWORD: abc123
      PGADMIN_LISTEN_PORT: "5050"
    ports:
      - "5050:5050"
    depends_on:
      - database16

  # Backend Java con Open Liberty
  pupas-backend:
    build: .
    container_name: pupas_backend
    ports:
      - "9080:9080"
      - "9443:9443"
    environment:
      DB_HOST: database16
      DB_NAME: tipicos_tpi135
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: abc123
    depends_on:
      database16:
        condition: service_healthy
    # Ya NO necesitas montar el .war desde el host
    volumes:
      - ./server.xml:/opt/ol/wlp/usr/servers/tpiserver_2025/server.xml
      - ./postgresql-42.7.5.jar:/opt/ol/wlp/lib/postgresql-42.7.5.jar
